pipeline {
    agent any 
    tools {
        maven 'M3'
    }
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/bou3108/node-stock-algeek.git'
            }
        }
        stage ('Publish package through SSH') {
            steps{
                script {
    				sshPublisher(publishers: [
    					sshPublisherDesc(configName: 'aws-stock-host', transfers: [
    						sshTransfer(
    							execCommand: '''
    								echo "Docker Clean Up";
                                    sudo docker stop node-stock-cont || true;
                                    sudo docker rm node-stock-cont || true;
                                    sudo docker rmi node-stock || true;
    								sudo rm -rf *;
                                    '''
                            ),
    						sshTransfer(
    							sourceFiles: "**/*",
    							removePrefix: "",
    							remoteDirectory: "//home//ec2-user",
    							execCommand: '''
    								ls -l /home/ec2-user;
    							'''
    						),
    						sshTransfer(
    							sourceFiles: "Dockerfile",
    							remoteDirectory: "//home//ec2-user",
    								execCommand: '''
                                        cd /home/ec2-user;
                                        sudo docker build -t node-stock .;
                                        sudo docker run -d --name node-stock-cont -p 5000:5000 node-stock;
                                    '''
                            )
                        ])
                    ])
                }
            }
        }
    }
}